spring:
  config:
    activate:
      on-profile: dev

  google:
    client-id: ${GOOGLE_CLIENT_ID:dev-client-id}
    client-secret: ${GOOGLE_CLIENT_SECRET:dev-client-secret}

  jpa:
    show-sql: true

  flyway:
    enabled: true

nexora:
  otp:
    expiration-minutes: 5
  jwt:
    secret: dev-secret-key-just-for-local-development
    expiration-ms: 86400000